name: mkdocs
on:
  push:
    branches:
      - master 
      # only for test
      - mkdocs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Env
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Migrate Files for Mkdocs
        run: ./mkdocs.py

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
